-- Run this in PostgreSQL / Neon SQL Editor to create the coupon redemptions tracking table

CREATE TABLE IF NOT EXISTS public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_id bigint,
  coupon_code text not null,
  user_id text not null,
  user_email text,
  payment_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
ALTER TABLE public.coupon_redemptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anyone to read coupon redemptions for validation"
ON public.coupon_redemptions FOR SELECT
USING (true);

CREATE POLICY "Allow authenticated users to insert coupon redemptions"
ON public.coupon_redemptions FOR INSERT
WITH CHECK (true);
